version: '3.8'

services:
  web:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - DEBUG=True
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=django
      - MONGO_PASSWORD=djangopassword
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo-1
    command: ["--auth"]  # Habilita la autenticación en MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Usuario administrador
      MONGO_INITDB_ROOT_PASSWORD: adminpassword  # Contraseña del usuario administrador

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
